version: "3.3"
services:
  redis:
    container_name: redis_ru102js
    image: redis/redis-stack-server:6.2.6-v12
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redisdata:/data
    environment:
      - REDIS_ARGS=--appendonly yes --save ""
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
